### PR TITLE
Added German translation

### PR DESCRIPTION
**Pull request by dmarku**
Deutsche Übersetzung hinzugefügt

### CODE REVIEW

**Comment by dmarku** [comment]
Hi, I've been using your reader on my tablet to read through some digital comics over the past few months and your app has been straightforward and effective at that. The only thing I've had trouble with was viewing two-page layouts. Thought I could at least provide a translation to my native tongue as a small thanks for this nice tool. 😄

**Comment by nkanaev** [comment]
thanks for your contribution, @dmarku! i'll have a look at the PR in the following weekend. may i ask you to add your name to contributors list in `README.md` as well?

**Comment by dmarku** [comment]
Done!

**Comment by nkanaev** [comment]
thanks for your contribution, @dmarku!

**Pull request merged**
